### ISSUE TITLE
Autocomplete results height is wrong

### ISSUE THREAD

**Issue by Keith94** [nathancahill/prioritize-url#13]
Firefox Nightly 58.0a
Windows 8

![2017-10-09_14-13-48](https://user-images.githubusercontent.com/5490615/31358905-601636f2-acfc-11e7-87bd-ca712c8be4cd.png)

**Comment by nathancahill** [comment]
You're welcome to play around with the numbers to get the height right. I neither use Nightly or Windows, so I won't be able to reproduce. Feel free to submit a PR if you fix it.

**Comment by Keith94** [comment]
Fixed by #14
