### ISSUE TITLE
Other changes you may add or mention

### ISSUE THREAD

**Issue by anewuser** [nathancahill/prioritize-url#2]
To hide "Visit..." or "Search...":

```
richlistitem[type*="heuristic"],
richlistitem:first-of-type[actiontype="searchengine"],
richlistitem[actiontype="visiturl"],
richlistitem[actiontype="keyword"] {
  display:none !important;
}
```

To make the dropmarker stay always visible:

```
#urlbar:not(:hover) > .urlbar-textbox-container > .urlbar-history-dropmarker {
  opacity: 1 !important;
}
```

To change the number of results, edit `browser.urlbar.maxRichResults` in `about:Config`.

Then you can customize the height of the dropdown panel based on your number of results:

```
richlistbox.autocomplete-richlistbox {
  height: auto !important;
  max-height: calc([desired height for each item] * [number of items]) !important;
}
```

**Comment by nathancahill** [comment]
Those are really good. I'll incorporate them as options.

The `height: auto` part is already there, needed it for changing the font size. Did not think maxRichResults worked after the new design, I'll have to try it again.

More generally, Firefox shouldn't need to calculate the total height anymore (height or max-height). I submitted this bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1293411

**Comment by anewuser** [comment]
I actually have `21` in `browser.urlbar.maxRichResults`, and `12` in the CSS calculation, so I see a scrollbar to get to the the 13th-20th items (the 1st item is the "Visit/Search..." thing, which I've hidden).

**Comment by nathancahill** [comment]
Sad day. `maxRichResults` doesn't affect anything for me on Mac OSX/FF 48. Maybe another addon is conflicting.
