### ISSUE TITLE
Bookmark titles appear before URLs

### ISSUE THREAD

**Issue by anewuser** [nathancahill/prioritize-url#3]
My bookmark entries aren't affected by your CSS code:

![screenshot-1](https://cloud.githubusercontent.com/assets/6733770/17565021/0039fc26-5f0c-11e6-9e70-7e4f4942cad0.png)

Can you reproduce this and make the appropriate modifications?

Firefox 48 on Linux.

**Comment by nathancahill** [comment]
Yes indeed, let me fix that. I don't use bookmarks so I didn't notice.

**Comment by nathancahill** [comment]
Fixed and updated on userstyles.org. Thanks!
